build: off
environment:
  global:
    REPO_DIR: lda
    PACKAGE_NAME: lda
    BUILD_COMMIT: 2.0.0
    BUILD_DEPENDS: "cython"
    TEST_DEPENDS: "scipy"
    WHEELHOUSE_UPLOADER_REGION: IAD
    WHEELHOUSE_UPLOADER_USERNAME: lda-worker
    WHEELHOUSE_UPLOADER_SECRET:
      secure: irUwkBHJdprBu763o02cCyAoFZIBImYGft43VnH+wYH6Z6qRxaucbqZhiJZ1eL7U

  matrix:
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python38
    - PYTHON: C:\Python38-x64
    - PYTHON: C:\Python39
    - PYTHON: C:\Python39-x64

matrix:
    fast_finish: true

install:
    # Fetch submodules
    - git submodule update --init --recursive
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    - python -m pip install -U pip

    # Fix MSVC builds for 64-bit Python. See:
    # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
    - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"
    # Check that we have the expected version and architecture for Python
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8)"

build_script:
    # Build wheel
    - pip install wheel
    - cd %REPO_DIR%
    # Install the dependencies of the project.
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - git checkout %BUILD_COMMIT%
    - python -m cython -3 lda/_lda.pyx
    - python setup.py bdist_wheel
    # Install the generated wheel package to test it
    - "pip install --pre --no-index --find-links dist/ lda"

test_script:
    # Change to a non-source folder to make sure we run the tests on the
    # installed library.
    - "mkdir empty_folder"
    - "cd empty_folder"
    - "python -m unittest discover lda"
    # Move back to the project folder
    - "cd .."

artifacts:
    - path: "%REPO_DIR%\\dist\\*"

on_success:
  # Upload the generated wheel package to Rackspace
  # On Windows, Apache Libcloud cannot find a standard CA cert bundle so we
  # disable the ssl checks.
  - pip install wheelhouse-uploader
  - ps: ls
  - "python -m wheelhouse_uploader upload
    --no-ssl-check --local-folder=dist --no-update-index --region=IAD wheels"
